dist: trusty
#sudo: required
sudo: false

language: cpp
warnings_are_errors: true

compiler:
# - gcc
 - clang

#addons:
#  apt:
#    packages:
#      - gcc-4.9
#      - clang-3.5
#      - cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
